CREATE SEQUENCE SEQ_MAGASINS 
	INCREMENT BY 1 START WITH 1 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER;



ALTER TABLE DW_PRODUITS ADD (
	CONSTRAINT fk_dwproduits_categories FOREIGN KEY (Code_Cat) REFERENCES DW_CATEGORIES (Code_Cat),
	CONSTRAINT fk_dwproduits_marques FOREIGN KEY (Code_Mar) REFERENCES DW_MARQUES (Code_Mar)
	);
	
ALTER TABLE DW_MAGASINS
	ADD CONSTRAINT fk_dwmagasins_geographies FOREIGN KEY (Code_Dep) REFERENCES DW_GEOGRAPHIES (Code_Dep);
	
ALTER TABLE DW_VENTES ADD (
	CONSTRAINT fk_dwventes_produits FOREIGN KEY (Code_Pro) REFERENCES DW_PRODUITS (Code_Pro),
	CONSTRAINT fk_dwventes_magasins FOREIGN KEY (Code_Mag) REFERENCES DW_MAGASINS (Code_Mag)
	);