title: "Portfolio Data - Brusny Ardesh NDALA"
description: "Portfolio de projets en Data Engineering, Data Analysis et Machine Learning"
author: "Brusny Ardesh NDALA"

theme: jekyll-theme-midnight
lang: fr

email: ndalabrusny@gmail.com
github_username: Brusny
linkedin: https://www.linkedin.com/in/Brusny-Ardesh-NDALA

markdown: kramdown
highlighter: rouge

header_pages:
  - index.md
  - projets.md
  - experience.md
  - competences.md
  - formation.md
  - contact.md

plugins:
  - jekyll-seo-tag
