title: "Portfolio Data - Brusny Ardesh NDALA"
description: "Portfolio de projets en Data Engineering, Data Analysis et Machine Learning"
author: "Brusny Ardesh NDALA"

theme: jekyll-theme-leap-day
lang: fr

email: ndalabrusny@gmail.com
github_username: Brusny
linkedin: https://www.linkedin.com/in/Brusny-Ardesh-NDALA
