INSERT INTO src1_marques VALUES (0, 'Inconnue');
INSERT INTO src1_marques VALUES (1, 'Duvivier');
INSERT INTO src1_marques VALUES (2, 'Simmons');
INSERT INTO src1_marques VALUES (3, 'Epeda');
INSERT INTO src1_marques VALUES (4, 'Treca');
INSERT INTO src1_marques VALUES (5, 'Dunlopillo');
INSERT INTO src1_marques VALUES (6, 'Whirlpool');
INSERT INTO src1_marques VALUES (7, 'Sauter');
INSERT INTO src1_marques VALUES (8, 'Faure');
INSERT INTO src1_marques VALUES (9, 'Brandt');
INSERT INTO src1_marques VALUES (10, 'Arthur Martin Electrolux');
INSERT INTO src1_marques VALUES (11, 'Scholtes');
INSERT INTO src1_marques VALUES (12, 'Vedette');
INSERT INTO src1_marques VALUES (13, 'Radiola');
INSERT INTO src1_marques VALUES (14, 'Indesit');
INSERT INTO src1_marques VALUES (15, 'Siemens');
INSERT INTO src1_marques VALUES (16, 'Thomson');
INSERT INTO src1_marques VALUES (17, 'JVC');
INSERT INTO src1_marques VALUES (18, 'Samsung');
INSERT INTO src1_marques VALUES (19, 'Sony');
INSERT INTO src1_marques VALUES (20, 'Philips');
COMMIT;
