INSERT INTO src1_categories VALUES (1, 'literie', NULL);
INSERT INTO src1_categories VALUES (2, 'matelas', 1);
INSERT INTO src1_categories VALUES (3, 'sommier', 1);
INSERT INTO src1_categories VALUES (4, 'ensemble relaxation', 1);
INSERT INTO src1_categories VALUES (5, 'meuble', NULL);
INSERT INTO src1_categories VALUES (6, 'lit', 5);
INSERT INTO src1_categories VALUES (7, 'mezzanine', 5);
INSERT INTO src1_categories VALUES (8, 'oreiller', 1);
INSERT INTO src1_categories VALUES (9, 'couette', 1);
INSERT INTO src1_categories VALUES (10, 'armoire', 5);
INSERT INTO src1_categories VALUES (11, 'chevet', 5);
INSERT INTO src1_categories VALUES (12, 'bureau', 5);
INSERT INTO src1_categories VALUES (13, 'commode', 5);
INSERT INTO src1_categories VALUES (14, 'electroménager', NULL);
INSERT INTO src1_categories VALUES (15, 'four', 14);
INSERT INTO src1_categories VALUES (16, 'plaque cuisson', 14);
INSERT INTO src1_categories VALUES (17, 'cuisinière', 14);
INSERT INTO src1_categories VALUES (18, 'lave-linge', 14);
INSERT INTO src1_categories VALUES (19, 'lave-vaisselle', 14);
INSERT INTO src1_categories VALUES (20, 'réfrigérateur', 14);
INSERT INTO src1_categories VALUES (21, 'hifi', NULL);
INSERT INTO src1_categories VALUES (22, 'caméscope', 21);
INSERT INTO src1_categories VALUES (23, 'dvd', 21);
INSERT INTO src1_categories VALUES (24, 'magnétoscope', 21);
INSERT INTO src1_categories VALUES (25, 'téléviseur', 21);
COMMIT;
